sudo: required
language: python
python:
  - 2.7
  - 3.4
os:
  - linux
  - osx
before_install:
  # work around https://github.com/travis-ci/apt-package-whitelist/issues/376
  - export filename="shellcheck_0.3.7-1_amd64.deb"
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/$filename"; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo dpkg -i "$filename"; fi
install: if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements.txt; fi
script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then shellcheck bin/{deploy,eups-copy-tag,mass-tag,publish,rebuild,rebuild-cron,setup.sh} etc/settings.cfg.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./bin/repos-lint ./etc/repos.yaml; fi
  # eups assumes 'python' is 2.7
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./bin/deploy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then . ./bin/setup.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./bin/rebuild cfitsio; fi
#matrix:
#  exclude:
#    - python: 3.4
#      os: osx
notifications:
  email: false
  hipchat:
    rooms:
      secure: hiu+I6yS6iQBguNNyuJ2H6HCUi2575zGgA74vuGIIViFPPF2Oc1Ty18u4ahygglaOzXh9FgFP0XEYhKE1FYPmeneP0bI/u9sr4ruEOUnC1xUyv1ClmsakzNZucQ2N7oeEEY0FOZK2VpQw44cisVdtVQFnTqf99Hj2fGP1+2LIWo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
