sudo: false
language: c
matrix:
  include:
    - os: linux
      language: python
      python: "3.4"
      env: MODE=lint
    - os: linux
      env: MODE=deploy
    - os: linux
      env: MODE=deploy-bleed
    - os: osx
      env: MODE=deploy
    - os: osx
      env: MODE=deploy-bleed
    - os: linux
      env: MODE=deploy3
    - os: linux
      env: MODE=deploy3-bleed
    - os: osx
      env: MODE=deploy3
    - os: osx
      env: MODE=deploy3-bleed
    - os: linux
      env: MODE=deploy-sims
    - os: osx
      env: MODE=deploy-sims
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  allow_failures:
    - os: osx
script: |
  case $MODE in
    lint)
      pip install -r requirements.txt
      ./bin/repos-lint ./etc/repos.yaml
      ;;
    deploy*)
      CONDA_PREFIX=""
      if [[ $MODE == deploy-bleed ]]; then
        echo -e "*** testing with BLEED Python 2 conda/pip packages ***\n"
        ./bin/deploy -b
      elif [[ $MODE == deploy3-bleed ]]; then
        echo -e "*** testing with BLEED Python 3 conda/pip packages ***\n"
        CONDA_PREFIX="3"
        ./bin/deploy -b -3
      elif [[ $MODE == deploy ]]; then
        echo -e "*** testing with PINNED Python 2 conda/pip packages ***\n"
        ./bin/deploy
      elif [[ $MODE == deploy3 ]]; then
        echo -e "*** testing with PINNED Python 3 conda/pip packages ***\n"
        CONDA_PREFIX="3"
        ./bin/deploy -3
      elif [[ $MODE == deploy-sims ]]; then
        echo -e "*** testing with PINNED Python 2 + BLEED sims conda/pip packages ***\n"
        CONDA_PREFIX="2"
        ./bin/deploy -s
      else
        echo -e "*** Unrecognized mode for deploy script ***\n"
        exit -1
      fi
      . ./bin/setup.sh
      case $(uname -s) in
        Linux*)
          conda_packages="conda${CONDA_PREFIX}_packages-linux-64.txt"
          ;;
        Darwin*)
          conda_packages="conda${CONDA_PREFIX}_packages-osx-64.txt"
          ;;
        *)
          echo "unsupported platform $(uname -s)"
          exit 1
          ;;
      esac
      echo -e "*** checking installed vs ${conda_packages} conda packages ***\n"
      conda list -e > "./etc/${conda_packages}"
      git diff
      rebuild cfitsio
      ;;
    *)
      echo "unknown MODE: $MODE"
      exit 1
      ;;
  esac
notifications:
  email: false
  hipchat:
    rooms:
      secure: hiu+I6yS6iQBguNNyuJ2H6HCUi2575zGgA74vuGIIViFPPF2Oc1Ty18u4ahygglaOzXh9FgFP0XEYhKE1FYPmeneP0bI/u9sr4ruEOUnC1xUyv1ClmsakzNZucQ2N7oeEEY0FOZK2VpQw44cisVdtVQFnTqf99Hj2fGP1+2LIWo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
