sudo: required
language: python
python:
  - 3.4
before_install:
  # work around https://github.com/travis-ci/apt-package-whitelist/issues/376
  - export filename="shellcheck_0.3.7-1_amd64.deb"
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/$filename"
  - sudo dpkg -i "$filename"
install: pip install -r requirements.txt
script:
  - shellcheck bin/{deploy,eups-copy-tag,mass-tag,publish,rebuild,rebuild-cron,setup.sh} etc/settings.cfg.sh
  - ./bin/repos-lint ./etc/repos.yaml
  - ./bin/deploy
  - . ./bin/setup.sh
  - ./bin/rebulid cfitsio
notifications:
  email: false
  hipchat:
    rooms:
      secure: hiu+I6yS6iQBguNNyuJ2H6HCUi2575zGgA74vuGIIViFPPF2Oc1Ty18u4ahygglaOzXh9FgFP0XEYhKE1FYPmeneP0bI/u9sr4ruEOUnC1xUyv1ClmsakzNZucQ2N7oeEEY0FOZK2VpQw44cisVdtVQFnTqf99Hj2fGP1+2LIWo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
